name: Deploy Node.js App

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.7'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create deployment package
      run: |
        mkdir -p /tmp/app-release
        cp -R . /tmp/app-release
        rm -rf /tmp/app-release/node_modules /tmp/app-release/.git
        tar -czf release.tar.gz -C /tmp/app-release .
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    
    - name: Add VM host key to known_hosts
      run: ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to VM
      run: |
        # Copy deployment package to VM
        scp release.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:/tmp/
        
        # Execute deployment commands
        ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "
          set -e
          mkdir -p ~/app
          tar -xzf /tmp/release.tar.gz -C ~/app
          cd ~/app
          
          # Confirm ecosystem file exists
          ls -la
          if [ ! -f 'ecosystem.config.js' ]; then
            echo 'ERROR: ecosystem.config.js file is missing!'
            exit 1
          fi
          
          # Install dependencies
          npm ci --production
          
          # Start/restart with PM2 using full path
          pm2 list
          pm2 restart ~/app/ecosystem.config.js || pm2 start ~/app/ecosystem.config.js
          
          # Clean up
          rm /tmp/release.tar.gz
        "